export const EXCEL_HEADER = {
  NAME: 'Name of Service',

  CARRIER: 'Carrier',

  SERVICE: 'Service',

  START_WEIGHT: 'Start range of weight',

  END_WEIGHT: 'End Range of Weight',

  MAX_WEIGHT: 'Max Weight',

  ADDITIONAL_WEIGHT: 'Add. Weight for applying charges',

  LOCAL_AMOUNT: 'LOCAL ZONE AMOUNT',

  LOCAL_ADDITIONAL_AMOUNT:
    'LOCAL ZONE ADDITIONAL AMOUNT',

  STATE_AMOUNT: 'STATE ZONE AMOUNT',

  STATE_ADDITIONAL_AMOUNT:
    'STATE ZONE ADDITIONAL AMOUNT',

  ROI_AMOUNT: 'ROI ZONE AMOUNT',

  ROI_ADDITIONAL_AMOUNT:
    'ROI ZONE ADDITIONAL AMOUNT',

  METRO_AMOUNT: 'METRO ZONE AMOUNT',

  METRO_ADDITIONAL_AMOUNT:
    'METRO ZONE ADDITIONAL AMOUNT',

  SPECIAL_AMOUNT: 'SPECIAL ZONE AMOUNT',

  SPECIAL_ADDITIONAL_AMOUNT:
    'SPECIAL ZONE ADDITIONAL AMOUNT',
} as const;